Update retype-action.yml

diff --git a/.github/workflows/retype-action.yml b/.github/workflows/retype-action.yml
--- a/.github/workflows/retype-action.yml
+++ b/.github/workflows/retype-action.yml
@@ -109,7 +109,7 @@ jobs:
 
   publish:
     name: Publish to retype branch
-    needs: [issues_to_markdown, generate_rss]
+    needs: issues_to_markdown
     runs-on: ubuntu-latest
 
     steps:
@@ -129,6 +129,50 @@ jobs:
         with:
           license: ${{ secrets.RETYPE_SECRET }}
           
+      # Generate RSS feed after building with Retype
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16
+
+      - name: Create package.json in /tmp
+        run: |
+          echo '{
+            "name": "tmp",
+            "version": "1.0.0",
+            "description": "",
+            "main": "index.js",
+            "scripts": {
+              "test": "echo \"Error: no test specified\" && exit 1"
+            },
+            "author": "",
+            "license": "ISC",
+            "dependencies": {
+              "rss": "^1.2.2",
+              "jsdom": "^16.7.0"
+            }
+          }' > /tmp/package.json
+  
+      - name: Install dependencies in /tmp
+        run: npm install --prefix /tmp
+  
+      - name: Copy script to a temporary location
+        run: |
+          cp .github/scripts/generate_rss.js /tmp/generate_rss.js
+  
+      - name: Generate RSS Feed
+        run: NODE_PATH=/tmp/node_modules node /tmp/generate_rss.js  # <-- Run script from /tmp
+  
+      - name: Commit and push if it's necessary
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          if [[ $(git status --porcelain) ]]; then
+            git add docs/rss.xml
+            git commit -m "Update rss.xml"
+            git push
+          fi
+
       - name: Push to retype branch
         uses: retypeapp/action-github-pages@latest
         with:
