Update retype-action.yml

diff --git a/.github/workflows/retype-action.yml b/.github/workflows/retype-action.yml
--- a/.github/workflows/retype-action.yml
+++ b/.github/workflows/retype-action.yml
@@ -64,20 +64,38 @@ jobs:
         with:
           node-version: 16
 
-      - name: Install dependencies
-        run: npm install rss jsdom
+      - name: Create package.json in /tmp
+        run: |
+          echo '{
+            "name": "tmp",
+            "version": "1.0.0",
+            "description": "",
+            "main": "index.js",
+            "scripts": {
+              "test": "echo \"Error: no test specified\" && exit 1"
+            },
+            "author": "",
+            "license": "ISC",
+            "dependencies": {
+              "rss": "^1.2.2",
+              "jsdom": "^16.7.0"
+            }
+          }' > /tmp/package.json
+  
+      - name: Install dependencies in /tmp
+        run: npm install --prefix /tmp
   
       - name: Copy script to a temporary location
         run: |
           cp .github/scripts/generate_rss.js /tmp/generate_rss.js
-
+  
       - name: Checkout code (retype)
         uses: actions/checkout@v3
         with:
           ref: retype  # <-- Switch to 'retype' branch
-
+  
       - name: Generate RSS Feed
-        run: node /tmp/generate_rss.js  # <-- Run script from /tmp
+        run: NODE_PATH=/tmp/node_modules node /tmp/generate_rss.js  # <-- Run script from /tmp
   
       - name: Commit and push if it's necessary
         run: |
@@ -88,7 +106,7 @@ jobs:
             git commit -m "Update rss.xml"
             git push
           fi
-          
+
   publish:
     name: Publish to retype branch
     needs: [issues_to_markdown, generate_rss]
